name: Daily Scraping FIDE Chess Player Rating

on:
  schedule:
    - cron: '*/5 * * * *'   # every 12 hours 0 */12 * * *


jobs:
  chess-rating-scrape:
    runs-on: macos-latest
    env:
      ATLAS_URL: ${{ secrets.ATLAS_URL }}
      ATLAS_COLLECTION: ${{ secrets.ATLAS_COLLECTION }}
      ATLAS_DB: ${{ secrets.ATLAS_DB }}
    steps:
      - name: Start time
        run: echo "$(date) ** $(TZ=Asia/Jakarta date)"
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install mongolite package
        run: Rscript -e 'install.packages("mongolite", dependencies = TRUE)'
      - name: Install rvest package
        run: Rscript -e 'install.packages("rvest", dependencies = TRUE)'        
      - name: Install tidyverse package
        run: Rscript -e 'install.packages("tidyverse", dependencies = TRUE)'
      - name: Install dplyr package
        run: Rscript -e 'install.packages("dplyr", dependencies = TRUE)'
      - name: Install XQuartz package
        run: Rscript -e 'install.packages("XQuartz", dependencies = TRUE)'
      - name: Install X11 package
        run: Rscript -e 'install.packages("X11", dependencies = TRUE)'
      - name: Scrape data 
        run: Rscript scrape.R

